---
- name: install Apache and php
  become: true
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - httpd
    - php
    - php-mysql
  tags: [ 'packages' ]

- name: create a simple index.php file to communicate with remote MySQL database
  become: true
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
    mode: 0644
  tags: [ 'configure' ]

- name: start Apache and make sure it's enabled for autostart
  become: true
  service: name=httpd state=started enabled=yes
