---
# install MySQL server, make it listen on all interfaces, allow incoming MySQL connections,
# make sure MySQL server is started and enabled for autostart, and add a database user
# (use role default variables to store database credentials).
- name: download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /home/ec2-user/get-pip.py
  tags: [ 'packages' ]

- name: install pip
  become: true
  command: python /home/ec2-user/get-pip.py
  tags: [ 'packages' ]

- name: install MariaDB server
  become: true
  yum:
    name:
      - mariadb-server
      - mariadb
      - MySQL-python
    state: present
  tags: [ 'packages' ]

- name: make MariaDB listen on all interfaces, allow incoming MariaDB connections
  become: true
  lineinfile:
    path: /etc/my.cnf
    line: "bind-address={{ ansible_eth0.ipv4.address }}"
  notify: restart mariadb

- name: start MariaDB and make sure it's enabled for autostart
  become: true
  service:
    name: mariadb
    state: started
    enabled: yes

- name: add a database user
  become: true
  mysql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_pass }}"
    host: '%'
