Parameters:
  cidrBlock:
    Description: "CIDR block for VPC."
    Type: String
    Default: 192.168.0.0/16
  cidrBlockSubnetA:
    Description: "CIDR block for Subnet A."
    Type: String
    Default: 192.168.1.0/24
  cidrBlockSubnetB:
    Description: "CIDR block for Subnet B."
    Type: String
    Default: 192.168.2.0/24
  ec2InstanceClass:
    Description: "EC2 instance class (a list of allowed values must be pre-defined, t2.micro being the default);"
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
  minInstance:
    Description: "minimum ASG instance count (a default value must be pre-defined)"
    Type: Number
    Default: 1
  maxInstance:
    Description: "maximum ASG instance count (a default value must be pre-defined)"
    Type: Number
    Default: 1
  keyPair:
    Description: "EC2 key pair name"
    Type: String
  DBInstanceClass:
    Description: "RDS instance class (a list of allowed values must be pre-defined)"
    Type: String
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.m1.small
      - db.m1.large
  SlowQueryLog:
    Description: "MySQL slow_query_log setting (allowed values: 0 or 1)"
    Type: Number
    AllowedValues:
      - 0
      - 1
  DBUsername:
    Description: "database username"
    Type: String
    MinLength: 4
    MaxLength: 15
    AllowedPattern: ^[a-zA-Z0-9]*$
  DBPassword:
    NoEcho: true
    Description: "database password (this value must not be visible when entered during stack creation)"
    Type: String
    MinLength: 5
    MaxLength: 10
    AllowedPattern: ^[a-zA-Z0-9]*$
Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        cidrBlock: !Ref cidrBlock
        cidrBlockSubnetA: !Ref cidrBlockSubnetA
        cidrBlockSubnetB: !Ref cidrBlockSubnetB
      TemplateURL: https://kutzhanov-backup.s3.amazonaws.com/cloudformation/networking.yml
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCid: !GetAtt NetworkingStack.Outputs.VPCid
      TemplateURL: https://kutzhanov-backup.s3.amazonaws.com/cloudformation/security_groups.yml
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        subnetA: !GetAtt NetworkingStack.Outputs.subnetAid
        subnetB: !GetAtt NetworkingStack.Outputs.subnetBid
        AdminSGid: !GetAtt SecurityGroupsStack.Outputs.AdminSGid
        RDSSGid: !GetAtt SecurityGroupsStack.Outputs.RDSSGid
        DBInstanceClass: !Ref DBInstanceClass
        SlowQueryLog: !Ref SlowQueryLog
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
      TemplateURL: https://kutzhanov-backup.s3.amazonaws.com/cloudformation/database.yml
  WebStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        subnetA: !GetAtt NetworkingStack.Outputs.subnetAid
        subnetB: !GetAtt NetworkingStack.Outputs.subnetBid
        ELBSG: !GetAtt SecurityGroupsStack.Outputs.ELBSGid
        EC2SG: !GetAtt SecurityGroupsStack.Outputs.EC2SGid
        ec2InstanceClass: !Ref ec2InstanceClass
        minInstance: !Ref minInstance
        maxInstance: !Ref maxInstance
        keyPair: !Ref keyPair
        RDSendpoint: !GetAtt DatabaseStack.Outputs.RDSendpoint
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
      TemplateURL: https://kutzhanov-backup.s3.amazonaws.com/cloudformation/web.yml
Outputs:
  ELBdomain:
    Description: ELB domain name
    Value: !GetAtt WebStack.Outputs.ELBdomain
